export const impostorCount = 1
export const meetingLength = 15
export const meetingCooldown = 15
export const taskCount = 2
export const sabotageLengths = {oxygen: 200000, reactor: 200000, comms: 20}
export const sabotageCooldown = 20
export const tasks = [
    {description: 'Align Engine Output', password: '1595'},
    {description: 'Align Telescope', password: '7756'},
    {description: 'Assemble Artifact', password: '4975'},
    {description: 'Build Sandcastle', password: '8958'},
    {description: 'Buy Beverage', password: '3634'},
    {description: 'Calibrate Distributor', password: '8948'},
    {description: 'Chart Course', password: '8411'},
    {description: 'Clean O2 Filter', password: '6100'},
    {description: 'Clean Toilet', password: '6515'},
    {description: 'Clean Vent', password: '9678'},
    {description: 'Clear Asteroids', password: '3446'},
    {description: 'Collect Shells', password: '5120'},
    {description: 'Cook Fish', password: '5556'},
    {description: 'Crank Generator', password: '6741'},
    {description: 'Decontaminate', password: '8509'},
    {description: 'Develop Photos', password: '7697'},
    {description: 'Divert Power', password: '1396'},
    {description: 'Dress Mannequin', password: '4065'},
    {description: 'Empty Garbage', password: '3759'},
    {description: 'Enter Id Code', password: '9016'},
    {description: 'Fill Canisters', password: '5944'},
    {description: 'Find Signal', password: '4373'},
    {description: 'Fix Antenna', password: '6944'},
    {description: 'Fix Shower', password: '4247'},
    {description: 'Fix Weather Node', password: '1887'},
    {description: 'Fix Wiring', password: '4817'},
    {description: 'Fuel Engines', password: '1995'},
    {description: 'Get Biggol Sword', password: '2382'},
    {description: 'Help Critter', password: '5566'},
    {description: 'Hoist Supplies', password: '1584'},
    {description: 'Insert Keys', password: '7083'},
    {description: 'Inspect Sample', password: '1290'},
    {description: 'Lift Weights', password: '4034'},
    {description: 'Make Burger', password: '5679'},
    {description: 'Measure Weather', password: '7594'},
    {description: 'Mine Ores', password: '6184'},
    {description: 'Monitor Tree', password: '9620'},
    {description: 'Open Waterways', password: '5468'},
    {description: 'Pick Up Towels', password: '9695'},
    {description: 'Polish Ruby', password: '6052'},
    {description: 'Prep Vegetables', password: '4504'},
    {description: 'Prime Shields', password: '7892'},
    {description: 'Process Data', password: '8411'},
    {description: 'Put Away Pistols', password: '6862'},
    {description: 'Put Away Rifles', password: '6627'},
    {description: 'Reboot Wifi', password: '3010'},
    {description: 'Record Temperature', password: '1720'},
    {description: 'Repair Drill', password: '5339'},
    {description: 'Replace Parts', password: '9723'},
    {description: 'Replace Water Jug', password: '7664'},
    {description: 'Reset Breakers', password: '3792'},
    {description: 'Rewind Tapes', password: '6689'},
    {description: 'Roast Marshmallow', password: '4535'},
    {description: 'Run Diagnostics', password: '8056'},
    {description: 'Scan Boarding Pass', password: '8982'},
    {description: 'Sort Records', password: '8828'},
    {description: 'Sort Samples', password: '8597'},
    {description: 'Stabilize Steering', password: '4534'},
    {description: 'Start Fans', password: '4991'},
    {description: 'Start Reactor', password: '4472'},
    {description: 'Store Artifacts', password: '2473'},
    {description: 'Submit Scan', password: '2754'},
    {description: 'Swipe Card', password: '5865'},
    {description: 'Throw Frisbee', password: '9203'},
    {description: 'Unlock Manifolds', password: '9665'},
    {description: 'Unlock Safe', password: '7348'},
    {description: 'Upload Data', password: '4496'},
    {description: 'Visual tasks', password: '2894'},
    {description: 'Water Plants', password: '3022'}
]